"""Render safe, inline-styled HTML for a WeChat Official Account article."""

from __future__ import annotations

import re
from collections.abc import Callable

from .markdown import render_markdown


WECHAT_THEMES = frozenset({"minimal", "tech", "warm"})

# 标签匹配正则
_TAG_PATTERN = re.compile(
    r"<(?P<tag>h[1-6]|blockquote|pre|code|ul|ol|li|hr|a|p|img)"
    r"(?P<attributes>[^>]*)>"
)
# 内联样式字典
_THEME_COLORS = {
    "minimal": {
        "heading": "#1f2937", "body": "#374151", "muted": "#6b7280",
        "accent": "#2563eb", "border": "#d1d5db", "rule": "#e5e7eb",
        "code_background": "#f3f4f6",
    },
    "tech": {
        "heading": "#0f172a", "body": "#334155", "muted": "#475569",
        "accent": "#0369a1", "border": "#38bdf8", "rule": "#bae6fd",
        "code_background": "#f0f9ff",
    },
    "warm": {
        "heading": "#4a2c20", "body": "#51372c", "muted": "#765548",
        "accent": "#b45309", "border": "#d97706", "rule": "#fde68a",
        "code_background": "#fffbeb",
    },
}

# 样式注入函数，从正则匹配中提取标签名和已有属性，从字典中取对应样式，拼接为带 style 属性的新标签；
def _inline_styles(theme: str) -> dict[str, str]:
    colors = _THEME_COLORS[theme]
    return {
        "h1": f"font-size:24px;line-height:1.4;margin:24px 0 16px;color:{colors['heading']};",
        "h2": f"font-size:21px;line-height:1.45;margin:22px 0 14px;color:{colors['heading']};",
        "h3": f"font-size:18px;line-height:1.5;margin:20px 0 12px;color:{colors['heading']};",
        "h4": f"font-size:16px;line-height:1.5;margin:18px 0 10px;color:{colors['heading']};",
        "h5": f"font-size:15px;line-height:1.5;margin:16px 0 8px;color:{colors['heading']};",
        "h6": f"font-size:14px;line-height:1.5;margin:14px 0 8px;color:{colors['heading']};",
        "p": f"font-size:16px;line-height:1.8;margin:0 0 16px;color:{colors['body']};",
        "ul": "padding-left:1.5em;margin:0 0 16px;",
        "ol": "padding-left:1.5em;margin:0 0 16px;",
        "li": f"font-size:16px;line-height:1.8;color:{colors['body']};",
        "blockquote": f"margin:16px 0;padding:12px 16px;border-left:4px solid {colors['border']};color:{colors['muted']};",
        "pre": f"overflow-x:auto;padding:12px 14px;margin:16px 0;background:{colors['code_background']};border-radius:6px;",
        "code": "font-family:monospace;",
        "hr": f"border:0;border-top:1px solid {colors['rule']};margin:24px 0;",
        "a": f"color:{colors['accent']};text-decoration:underline;",
        "img": "max-width:100%;height:auto;display:block;margin:12px auto;",
    }


def _add_inline_styles(html_content: str, *, theme: str) -> str:
    styles = _inline_styles(theme)

    def replace_tag(match: re.Match[str]) -> str:
        tag = match.group("tag")
        attributes = match.group("attributes")
        style = styles[tag]
        return f'<{tag}{attributes} style="{style}">'

    return _TAG_PATTERN.sub(replace_tag, html_content)

# 主入口函数
def render_wechat_html(
    markdown: str,
    *,
    theme: str = "minimal",
    image_renderer: Callable[[str, str], str] | None = None,
) -> str:
    """Convert the supported Markdown subset into safe WeChat HTML.

    Markdown is rendered by the existing escaping renderer first.  Only tags
    generated by that renderer receive inline styles, so raw HTML and scripts
    remain text and cannot become executable content.
    """

    if theme not in WECHAT_THEMES:
        raise ValueError("unsupported WeChat theme")
    return _add_inline_styles(
        render_markdown(markdown, image_renderer=image_renderer),
        theme=theme,
    )


__all__ = ["WECHAT_THEMES", "render_wechat_html"]
