"""Build validated WeChat Official Account draft payloads."""

from __future__ import annotations

from typing import Any

from ..models import Article


class WeChatDraftValidationError(ValueError):
    """Raised when an Article cannot be represented as a WeChat news draft."""

    def __init__(self, error_code: str, message: str) -> None:
        super().__init__(message)
        self.error_code = error_code


WECHAT_TITLE_MAX_LENGTH = 32


def validate_wechat_title(title: str) -> str:
    """Validate the title before creating an external WeChat draft."""

    normalized = _require_text(title, "title")
    if len(normalized) > WECHAT_TITLE_MAX_LENGTH:
        raise WeChatDraftValidationError(
            "wechat_title_too_long",
            (
                "The WeChat title is too long: "
                f"{len(normalized)} characters; maximum is "
                f"{WECHAT_TITLE_MAX_LENGTH}."
            ),
        )
    return normalized


def _require_text(value: str, field_name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise WeChatDraftValidationError(
            f"wechat_{field_name}_missing",
            f"{field_name} must not be empty",
        )
    return value.strip()


def build_wechat_news_draft(
    article: Article,
    *,
    content_html: str,
    thumb_media_id: str,
    author: str | None = None,
    content_source_url: str | None = None,
) -> dict[str, Any]:
    """Build the JSON body for WeChat's ``draft/add`` endpoint.

    The caller must provide HTML generated by ``render_wechat_html``.  This
    function validates the platform fields but does not perform HTTP calls or
    change the Article state.
    """

    title = validate_wechat_title(article.title)

    normalized_author = author.strip() if isinstance(author, str) else None
    if normalized_author and len(normalized_author) > 16:
        raise WeChatDraftValidationError(
            "wechat_author_too_long",
            "author exceeds the WeChat limit",
        )

    digest = article.excerpt.strip()
    if len(digest) > 128:
        raise WeChatDraftValidationError(
            "wechat_digest_too_long",
            "digest exceeds the WeChat limit",
        )

    normalized_content = _require_text(content_html, "content")
    lowered_content = normalized_content.casefold()
    if "<script" in lowered_content or "javascript:" in lowered_content:
        raise WeChatDraftValidationError(
            "wechat_content_unsafe",
            "content contains an unsafe construct",
        )

    normalized_thumb_media_id = _require_text(
        thumb_media_id,
        "thumb_media_id",
    )

    item: dict[str, Any] = {
        "article_type": "news",
        "title": title,
        "digest": digest,
        "content": normalized_content,
        "thumb_media_id": normalized_thumb_media_id,
        "need_open_comment": 0,
        "only_fans_can_comment": 0,
    }
    if normalized_author:
        item["author"] = normalized_author
    if content_source_url is not None:
        item["content_source_url"] = _require_text(
            content_source_url,
            "content_source_url",
        )

    return {"articles": [item]}


__all__ = [
    "WeChatDraftValidationError",
    "WECHAT_TITLE_MAX_LENGTH",
    "build_wechat_news_draft",
    "validate_wechat_title",
]
